Task 1: Variables declaration
osechka333/js-basic pull request #2
Opened 2019-10-07 17:26 UTC by osechka333

2019-10-08 09:00 UTC, Mike-Savin requested changes

2019-10-08 09:00 UTC, Mike-Savin commented on Exercises/variables-declaration/variables-declaration.js
> +  Age = (userAge < 18) ? 'Forbidden to vote' : 'Allowed to vote';
Great job in general)

It's a bad practice to assign a value to a variable without defining it. In your case `Age` variable will become global despite it was assigned only in the function and never declared before. It may cause bugs and unexpected behavior in your code)
And if you run your code in strict mode (http://javascript.info/strict-mode) the code will fail because you tried to assign a value to not declared variable.

Also by the naming convention all the variables and function names should not start with capital letters (more info: http://javascript.info/variables#variable-naming).

2019-10-08 14:30 UTC, lizarusi requested changes
All good, just see @Mike-Savin comments

2019-10-08 14:30 UTC, lizarusi commented on Exercises/variables-declaration/variables-declaration.js
> +var userTemperature = 96.8;
better even `userTemperature = 96.8;`

2019-10-08 15:08 UTC, osechka333 commented on Exercises/variables-declaration/variables-declaration.js
> +  Age = (userAge < 18) ? 'Forbidden to vote' : 'Allowed to vote';
thanks for the comment! I fixed these moments and got knowledge about the strict mode. It was really useful

2019-10-08 15:12 UTC, osechka333 commented on Exercises/variables-declaration/variables-declaration.js
> +var userTemperature = 96.8;
I tried to run without var/let in VS code 
userTemperature = 96.8;
console.log(userTemperature);
and I got the error while running: ReferenceError: userTemperature is not defined

but it works in JS bin

2019-10-09 11:49 UTC, lizarusi approved these changes
Perfect :)

2019-10-09 11:52 UTC, merged