Task: Arrays
osechka333/js-basic pull request #8
Opened 2019-11-18 22:30 UTC by osechka333

2019-11-19 08:01 UTC, lizarusi requested changes

2019-11-19 08:01 UTC, lizarusi commented on Exercises/arrays/arrays.js
> +function generateArray() {
consider using `Array.from`

2019-11-19 08:01 UTC, lizarusi commented on Exercises/arrays/arrays.js
> +  return results;
just `return [...array]`

2019-11-19 08:01 UTC, lizarusi commented on Exercises/arrays/arrays.js
> +  const results = arr.indexOf(element);
no need to use plural here

2019-11-19 08:01 UTC, lizarusi commented on Exercises/arrays/arrays.js
> +  return results;
just `return arrayOne.concat(arrayTwo)` also not good to use numbers in variables

2019-11-20 13:15 UTC, osechka333 commented on Exercises/arrays/arrays.js
> +function generateArray() {
thanks for comments! Updated and created new PR

2019-11-23 15:58 UTC, Mike-Savin approved these changes

2019-11-24 13:00 UTC, merged